### ISSUE TITLE
[Bug] V10 - uncaught Type Error

### ISSUE THREAD

**Issue by SesuUisu** [YourFavouriteOreo/VTT-Chat-Reactions#14]
When trying to add a reaction, nothing happens and the console shows:

chatreactions.js:2 Uncaught TypeError: Cannot read properties of undefined (reading 'togglePicker')
[Detected 1 package: chatreactions]
    at HTMLButtonElement.<anonymous> (chatreactions.js:2:253290)
(anonymous) @ chatreactions.js:2

**Comment by SesuUisu** [comment]
Second error message connected to Chat Reaction:


foundry.js:711 Error: Setting Model Validation Errors
[Setting.value]: may not be undefined
[No packages detected]
    at SchemaField._validateType (commons.js:3636:15)
    at SchemaField.validate (commons.js:3363:37)
    at Setting.validate (commons.js:5016:35)
    at new DataModel (commons.js:4793:26)
    at new Document (commons.js:5332:3)
    at new BaseSetting (commons.js:9342:3)
    at new ClientDocumentMixin (foundry.js:12999:5)
    at new Setting (foundry.js:21220:1)
    at ClientSettings.get (foundry.js:2737:21)
    at SettingsConfig._prepareCategoryData (foundry.js:71086:31)
    at SettingsConfig.getData (foundry.js:59170:23)
    at SettingsConfig._render (foundry.js:5014:29)
    at SettingsConfig._render (foundry.js:5739:17)
    at SettingsConfig._render (foundry.js:59239:18)
onError @ foundry.js:711
🎁call_wrapped @ libWrapper-wrapper.js:511
🎁Hooks.onError#lib-wrapper @ listeners.js:137
🎁Hooks.onError#0 @ libWrapper-wrapper.js:187
(anonymous) @ foundry.js:4975
Promise.catch (async)
render @ foundry.js:4973
_onSettingsButton @ foundry.js:75814
dispatch @ jquery.min.js:2
y.handle @ jquery.min.js:2

**Comment by YourFavouriteOreo** [comment]
Should be fixed and working now
